### ISSUE TITLE
title isn't unset after closing file

### ISSUE THREAD

**Issue by sewnie** [erf/vis-title#4]

**Comment by sewnie** [comment]
actually nvm doesn't seem to be possible

**Comment by erf** [comment]
Yes, i don't think it is possible. I tried it before. The shell should handle this though (i think). If you find a way to fix this, make a PR

**Comment by sewnie** [comment]
Why was this closed? i am literally currently working on it.

**Comment by erf** [comment]
I saw your comment it wasn't possible.

Also I tried something similar before like here: 
d574b2bbfc1282d536f97194239a76824d50030f

or by clearing it .. see previous commits .. but i think it wasn't working cross platform and the shell set's the title when exiting .. 

but if you find a solution for this, make a PR as i suggested
